export const types = {
    FETCH_POSTS_REQUEST: "FETCH_POSTS_REQUEST",
    FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
    FETCH_POSTS_FAIL: "FETCH_POSTS_FAIL",
    FETCH_COMMENTS_REQUEST: "FETCH_COMMENTS_REQUEST",
    FETCH_COMMENTS_SUCCESS: "FETCH_COMMENTS_SUCCESS",
    FETCH_COMMENTS_FAIL: "FETCH_COMMENTS_FAIL",
};