export const types = {
  // fetch posts
  FETCH_POSTS_REQUEST: "FETCH_POSTS_REQUEST",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAIL: "FETCH_POSTS_FAIL",

  //fetch one post
  FETCH_ONE_POST_REQUEST: "FETCH_ONE_POST_REQUEST",
  FETCH_ONE_POST_SUCCESS: "FETCH_ONE_POST_SUCCESS",
  FETCH_ONE_POST_FAIL: "FETCH_ONE_POST_FAIL",

  //fetch comments
  FETCH_COMMENTS_REQUEST: "FETCH_COMMENTS_REQUEST",
  FETCH_COMMENTS_SUCCESS: "FETCH_COMMENTS_SUCCESS",
  FETCH_COMMENTS_FAIL: "FETCH_COMMENTS_FAIL",

  //add comment
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAIL: "ADD_COMMENT_FAIL",
};
